### ISSUE TITLE
Can't run app

### ISSUE THREAD

**Issue by Piotr-Wosinek** [adderthorn/Monocast#1]
Hello,

I see load failed for:
C:\+APPS\SyndicationFeedReaderWriter\src\Microsoft.SyndicationFeed.ReaderWriter.csproj

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1104	Unable to find project 'C:\+APPS\SyndicationFeedReaderWriter\src\Microsoft.SyndicationFeed.ReaderWriter.csproj'. Check that the project reference is valid and that the project file exists.	Monocast	C:\+APPS\Monocast-master\Monocast\Monocast.csproj	1	

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1104	Unable to find project 'C:\+APPS\SyndicationFeedReaderWriter\src\Microsoft.SyndicationFeed.ReaderWriter.csproj'. Check that the project reference is valid and that the project file exists.	Monosoftware.Podcast	C:\+APPS\Monocast-master\Mono.Podcasts\Monosoftware.Podcast.csproj	1

**Comment by adderthorn** [comment]
Hello,

I do not mention this anywhere, my apologies. You will need to clone [this repository](https://github.com/adderthorn/SyndicationFeedReaderWriter) in the same root directory as Monocast. Monocast relies on the SyndicationFeedReaderWriter library.

**Comment by Piotr-Wosinek** [comment]
yes, now working, 

thx
